config/routes.rb
Rails.application.routes.draw do

  root 'home#top'

  devise_for :users
  
  resources :users, only:[:index, :edit, :update, :show] do
    resource :relationships, only:[:create, :destroy]
    get :follows, on: :member
    get :folowers, on: :member
  end

  get '/users/:id' => 'users#show'

  
  resources :circles do
    resource :circle_users,only: [:create,:destroy]
    resources :circle_events
    resource :circle_talks,only: :create
    resource :circle_likes,only: [:create,:destroy],as: "likes"
  end



  post "/circle_events/:id/talks" => "circle_event_talks#create",as: "circle_event_talks"
  post "/circles/:circle_id/circle_events/:id/attend" =>"circle_event_tickets#create",as: "circle_event_attend"
  delete "/circles/:circle_id/circle_events/:id/attend" =>"circle_event_tickets#destroy",as: "destroy_circle_event_attend"
  post "/circles/:circle_id/circle_events/:id/attend/:ticket_id" =>"circle_event_tickets#approve",as: "approve_circle_event_attend"

end

app/models/circle.rb
class Circle < ActiveRecord::Base

	mount_uploader :image,ImageUploader

	has_many :circle_users,dependent: :destroy
	has_many :circle_members,through: :circle_users,source: :user
	has_many :circle_events,dependent: :destroy
	has_many :circle_talks,dependent: :destroy

	has_many :circle_likes


	validates :name,presence: true

	validate :add_error_sample

	def add_error_sample
		if name.empty?
			errors[:base] << "サークル名を入力してください"
		end
		if desc.empty?
			errors[:base] << "サークル概要を入力してください"
		end
	end


	def circle_member?(circle,user)
		circle_users.where(circle_id: circle.id,user_id: user.id).exists?
	end

	def circle_liked?(user)
		circle_likes.where(user_id: user.id).exists?
	end

end

app/models/circle_event.rb
class CircleEvent < ActiveRecord::Base

	belongs_to :circle
	belongs_to :author,foreign_key: :author_id,class_name: User

	has_many :circle_event_tickets	
	has_many :circle_event_members,through: :circle_event_tickets,source: :user

	has_many :circle_event_talks

	has_one :circle_event_location

	validates :title,presence: true
	validates :desc,presence: true
	validates :author_id,presence: true


	def event_pending?(event)
		circle_event_tickets.where(circle_event_id: event.id,confirm: false)
	end

	def ticket_status?(circle_event,user,status)
		circle_event_tickets.where(circle_event_id: circle_event.id,user_id: user.id,confirm: status)		
	end

	def event_participants(circle_event)
		circle_event_tickets.where(circle_event_id: circle_event.id,confirm: true)
	end

	mount_uploader :image,CircleEventImageUploader

end

app/models/circle_event_location.rb
class CircleEventLocation < ActiveRecord::Base

	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode

	belongs_to :circle_event

end

app/models/circle_event_talk.rb
class CircleEventTalk < ActiveRecord::Base


	belongs_to :user
	belongs_to :circle_event


end

app/models/circle_event_ticket.rb
class CircleEventTicket < ActiveRecord::Base

	belongs_to :circle_event
	belongs_to :user

	validates :circle_event_id,presence: true
	validates :user_id,uniqueness: { scope: [:circle_event_id] }

end

app/models/circle_like.rb
class CircleLike < ActiveRecord::Base

	belongs_to :user
	belongs_to :circle

	validates :user,presence: true
	validates :user_id,uniqueness: { scope: :circle_id}
	validates :circle,presence: true


end

app/models/circle_talk.rb
class CircleTalk < ActiveRecord::Base

	belongs_to :circle
	belongs_to :user

	validates :circle_id,presence: true
	validates :user_id,presence: true
	validates :body,presence: true


end

app/models/circle_user.rb
class CircleUser < ActiveRecord::Base

	belongs_to :circle
	belongs_to :user

	validates :user_id,uniqueness: { scope: :circle_id }

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: User
	belongs_to :following, class_name: User

	validates :follower_id, presence: true
	validates :following_id, presence: true
	validates :following_id, uniqueness: {scope: :follower_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :relationships, foreign_key: :follower_id
   has_many :followings, through: :relationships

   has_many :inverse_follows, foreign_key: :following_id, class_name: Relationship
   has_many :followers, through: :inverse_follows

   has_many :circle_likes

   has_one :user_prof

   def followed_by? user
   	inverse_follows.where(follower_id: user.id).exists?
   end

  has_many :circle_users,dependent: :destroy
  has_many :circle_talks
  has_many :circle_events
  has_many :circle_event_tickets
  has_many :circle_event_talks
  
end

app/models/user_prof.rb
class UserProf < ActiveRecord::Base

	belongs_to :user


end

app/controllers/circle_events_controller.rb
class CircleEventsController < ApplicationController

	layout 'circle'

	before_action :authenticate_user!, except: :index
	before_action :set_circle
	before_action :event_authentication,only: [:new,:create,:update,:destroy]

	def index
		@circle_events = CircleEvent.where(circle_id: params[:circle_id]).order('created_at DESC').page(params[:page]).per(10)
		@circle = Circle.find(params[:circle_id])

	end

	def show
		@circle_event = CircleEvent.find(params[:id])
		@circle_event_talks = @circle_event.circle_event_talks
		@location = @circle_event.circle_event_location
	end

	def new
		@circle_event = CircleEvent.new		
	end

	def create
		circle_event = CircleEvent.new(circle_event_params)
		circle_event.circle_id = params[:circle_id] 
		circle_event.author_id = current_user.id

		if circle_event.save
			@location = CircleEventLocation.new
			@location.address =  circle_event.place
			@location.circle_event_id = circle_event.id
			@location.save
			redirect_to circle_circle_events_path(@circle),notice: "イベント作成に成功しました"
		else
			redirect_to new_circle_circle_event_path(@circle),alert: "イベント作成に失敗しました"
		end
	end

	def edit
		@circle_event = CircleEvent.find(params[:id])
	end

	def update
		@circle_event = CircleEvent.find(params[:id])
		if @circle_event.update(circle_event_params)
			redirect_to circle_circle_event_path(@circle,params[:id]),notice: "イベント内容を更新しました"
		else
			redirect_to :new,alert: "イベント内容の更新に失敗しました"
		end
	end

	def destroy
		@circle_event = CircleEvent.find(params[:id])
		@circle_event.destroy
		redirect_to circle_circle_events_path,notice: "イベントを削除しました"
	end

	private 
	def circle_event_params
		params.require(:circle_event).permit(:title,:desc,:event_date,:place,:one_phrase,:image)
	end

	def set_circle
		@circle = Circle.find(params[:circle_id])
	end

	def event_authentication
		unless current_user.circle_users.where(circle_id: params[:circle_id]).exists?
			redirect_to circle_circle_events_path
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end


	def follows
		@user = User.find(params[:id])
	end
	def followers
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circle_events_helper.rb
module CircleEventsHelper
end

app/helpers/circle_likes_helper.rb
module CircleLikesHelper
end

app/helpers/circle_talks_helper.rb
module CircleTalksHelper
end

app/helpers/circle_users_helper.rb
module CircleUsersHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circle_events/_form.html.erb
  
<%= form_for([circle,@circle_event]) do |f| %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class='input-group date'>
    <%= f.text_field :event_date, class: 'datepicker form-control' %>
    <span class="input-group-addon">
      <span class="fa fa-calendar"></span>
    </span>
  </div>
   <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
   <div class="field">
    <%= f.label :one_phrase %><br>
    <%= f.text_field :one_phrase %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit submit_message %>
  </div>

<% end %>

app/views/circle_events/edit.html.erb
<%= render "form",submit_message: "編集",circle: @circle %>

<%= link_to "イベント詳細にもどる",circle_circle_event_path(@circle,@circle_event) %>

app/views/circle_events/index.html.erb
<div class="contents-index clearfix">
	<div class="side">
		<div class="side-top clearfix">
			<% if current_user.circle_users.where(circle_id: params[:circle_id]).exists? %>
				<%= button_to "サークルページ",circle_path(@circle),class: "btn btn-primary circle-link-pri",method: :get %>
				<%= button_to "イベント新規作成",new_circle_circle_event_path(@circle),class: "btn btn-success new-event-link",method: :get %>
			<% else %>
				<%= button_to "サークルページ",circle_path(@circle),class: "btn btn-primary circle-link-pub",method: :get %>
			<% end %>
		</div>
		<!-- /.side-top -->
		<div class="side-contents">
			<% if @circle.image? %>
    	    	<%= image_tag @circle.image.url,class: "circle-image" %></td>
      		<% else %>
            	<%= image_tag "circle_img_dafault_gray.png",class: "circle-image"%>
        	<% end %>
	        <p class="circle-name"><%= @circle.name %></p>
    	    <p class="circle-desc"><%= @circle.desc %></p>
    	    <div class="circle-status clearfix">
        		<p class="circle-user-count"><i class="fa fa-user-plus" aria-hidden="true"></i><%= @circle.circle_members.count %></p>	
        		<% if @circle.circle_liked?(current_user) %>
        			<p class="circle-likes"><a rel="nofollow" data-method="delete" href="/circles/<%= @circle.id %>/circle_likes"><i class="fa fa-thumbs-up" aria-hidden="true"></i><%= @circle.circle_likes.count %></a></p>
        		<% else %>		
        			<p class="circle-likes"><a rel="nofollow" data-method="post" href="/circles/<%= @circle.id %>/circle_likes"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i><%= @circle.circle_likes.count %></a></p>		
				<% end %>
			</div>
			<!-- /.circle-status -->
		</div>
		<!-- /.side-contents  -->
	</div>
	<!-- /.side -->
	<div class="main">
		<div class="circle-events clearfix">
			<% @circle_events.each do |circle_event| %>
				<div class="circle-event clearfix">
					<% if circle_event.image? %>
						<%= image_tag circle_event.image.url,class: "circle-event-image" %>
					<% else %>
						<%= image_tag "circle_img_dafault_gray.png",class: "circle-event-image" %>
					<% end %>
					<div class="circle-event-prof">
						<p>イベント名: <%= link_to circle_event.title ,circle_circle_event_path(@circle,circle_event) %></p>
						<p>概要:<%= circle_event.desc %></p>
					</div>
					<!-- /.circle-event-prof -->
				</div>
				<!-- /.circle-event -->
			<% end %>
		</div>
		<!-- /.circle-events -->
		<div class="pagination">
			<%= paginate @circle_events %>			
		</div>
		<!-- /.paginatino -->
	</div>
	<!-- /.main -->
</div>
<!-- /.contents-index -->

app/views/circle_events/new.html.erb
<%= render "form",submit_message: "新規作成",circle: @circle %>

<%= link_to "一覧へもどる",circle_circle_events_path(@circle)%>

app/views/circle_events/show.html.erb
<div class="contents-show clearfix">
	<div class="main">
		<div class="main-top">
			<%= button_to "イベント一覧",circle_circle_events_path(@circle_event.circle),class: "btn btn-primary",method: :get %>
		</div>
		<!-- /.main-top -->
		<div class="main-contents">
			<h5><span class="heading">主催者</span></h5>
			<p><%= @circle_event.author.email %></p>
			<h5><span class="heading">イベント名</span></h5>
			<p><%= @circle_event.title %></p>
			<h5><span class="heading">イベント詳細</span></h5>
			<p><%= @circle_event.desc %></p>
			<h5><span class="heading">日時</span></h5>
			<% if @circle_event.event_date.blank? %>
				<p></p><br/>
			<% else %>
				<p><%= @circle_event.event_date %></p>
			<% end %>
			<h5><span class="heading">主催者のメッセージ</span></h5>
			<% if @circle_event.one_phrase.blank? %>	
				<p></p><br/>
			<% else %>
				<p><%= @circle_event.one_phrase %></p>
			<% end %>
			<h5><span class="heading">場所</span></h5>
			<% if @circle_event.place.blank? %>
				<p></p><br/>
			<% else %>
				<p><%= @circle_event.place %></p>
				<div id="map"></div>
			<% end %>

			<div class="event-apply">
				<% if @circle_event.ticket_status?(@circle_event,current_user,false).exists? %>
					<h5><span class="heading">申し込み状況</span></h5>
					<p>承認待ち</p>
				<% elsif @circle_event.ticket_status?(@circle_event,current_user,true).exists? %>
					<h5><span class="heading">申し込み状況</span></h5>
					<p>参加承認済み</p>
					<%= button_to "参加キャンセル",destroy_circle_event_attend_path(@circle_event.circle,@circle_event),class: "btn btn-info btn-sm",method: :delete %>
				<% else %>
					<%= button_to "参加申し込み",circle_event_attend_path(@circle_event.circle,@circle_event),class: "btn btn-warning",method: :post %>
				<% end %>
			</div>
			
		</div>
		<!-- /.main-contents -->
	</div>
	<!-- /.main -->
	<div class="side">
		<div class="side-contents">
			<ul class="nav nav-tabs" role="tablist">
	    		<li role="presentation" class="active"><a href="#event-members" aria-controls="home" role="tab" data-toggle="tab">メンバー</a></li>
	    		<% if @circle_event.ticket_status?(@circle_event,current_user,true).exists? %>
			    	<li><a data-toggle="modal" data-target="#eventTalk">トーク</a></li>
			    <% end %>
			    <% if current_user.id == @circle_event.author.id %>
			    <li role="presentation"><a href="#approve" aria-controls="settings" role="tab" data-toggle="tab">参加承認待ち<span class="badge"><%= @circle_event.event_pending?(@circle_event).count %></span></a></li>
			    <li class="dropdown">
		            <a class="dropdown-toggle" data-toggle="dropdown">設定<i class="fa fa-cog" aria-hidden="true"></i></a>
		            <ul class="dropdown-menu">
		            	<li><%= link_to 'イベント編集', edit_circle_circle_event_path(@circle_event.circle,@circle_event) %></li>
		            	<li><%= link_to 'イベント削除', circle_circle_event_path(@circle_event.circle,@circle_event),method: :delete %></li>
		            </ul>
		         </li>
			    <% end %>
		  	</ul>
		  	<!-- /.nav-tabs -->
		  	<div class="tab-content">
			    <div class="tab-pane active" id="event-members">
				    <div class="circle-event-member clearfix">
			            <% @circle_event.event_participants(@circle_event).each do |ticket| %>
			                <div class="event-user">
			                    <% if ticket.user.user_prof.try(:image) %>
			                    	<%= image_tag ticket.user_prof.image.url,class: 'user-image img-circle' %>
			         			<% else %>
			            			<%= image_tag 'user_noimage_default.png',class: 'user-image img-circle' %>
			          			<% end %>
			          			<p><%= ticket.user.email %></p>
			        		</div>
			        		<!-- /.event-user -->
			      		<% end %>
			    	</div>
			    	<!-- /.circle-event-member -->
			    </div>
			  	<!-- /#event-members -->
			  	<div class="tab-pane" id="approve">
			  		<div class="event-attend-member">
			  			<% @circle_event.event_pending?(@circle_event).each do |ticket| %>
			  				<div class="attend-user">
			                    <% if ticket.user.user_prof.try(:image) %>
			                    	<%= image_tag ticket.user_prof.image.url,class: 'user-image img-circle' %>
			         			<% else %>
			            			<%= image_tag 'user_noimage_default.png',class: 'user-image img-circle' %>
			          			<% end %>
			          			<p><%= ticket.user.email %></p>
			          			<%= button_to "承認する",approve_circle_event_attend_path(@circle_event.circle,@circle_event,ticket.id),class: "btn btn-danger" %>
			        		</div>
			        		<!-- /.attend-user -->
						<% end %>
			  		</div>
			  		<!-- /.event-attend-member -->
			  	</div>
			  	<!-- /#approve -->
			</div>
			<!-- /.tab-content -->
		</div>
		<!-- /.side-contents -->
	</div>
	<!-- /.side -->
</div>
<!-- /.contents-show -->

<div class="modal fade" id="eventTalk" tabindex="-1">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
				<h4 class="modal-title">イベントトーク</h4>
			</div>
			<!-- /.modal-header -->
			<div class="modal-body">
				<div class="clearfix" id='eventMessages'>
		        <% @circle_event_talks.each do |event_talk| %>
		            <% if event_talk.user.id == current_user.id %>
		            	<div class="message my-msg clearfix">
		                	<div class="user-info">
		                		<% if current_user.user_prof.try(:image) %>
		                    		<%= image_tag current_user.user_prof.image.url,class: "msg-user-image img-circle" %>
		                    	<% else %>
		                    		<%= image_tag 'user_noimage_default.png',class: "msg-user-image img-circle" %>
		                    	<% end %>
		                  		<p class="msg-user-name"><%= event_talk.user.email%></p>
		                	</div>
		                	<p class="msg-body"><%= event_talk.body %></p>
						</div>
		            <% else %>
		                <div class="message oth-msg clearfix">
		               		<div class="user-info">
		                 		<% if event_talk.user.user_prof.try(:image) %>
		                    		<%= image_tag event_talk.user.user_prof.image.url,class: "msg-user-image img-circle" %>
		                  		<% else %>
		                    		<%= image_tag 'user_noimage_default.png',class: "msg-user-image img-circle" %>
		              		    <% end %>
		                  		<p class="msg-user-name"><%= event_talk.user.email%></p>
		                	</div>
		                	<p class="msg-body"><%= event_talk.body %></p>
		              	</div>
		            <% end %>
		        <% end %>
		        </div>
				<%= form_tag(circle_event_talks_path(@circle_event),:remote => true) do %>
					<%= text_field_tag :body %>
					<%= submit_tag "送信" %>
				<% end %>
			</div>
			<!-- /.modal-body -->
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
			<!-- /.modal-footer -->
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>

<script>
  Pusher.logToConsole = true;

  var pusher = new Pusher('26f18dcdcf80c348ef52', {
    encrypted: true
  });

  var line = "circle_event_talk_<%= @circle_event.id.to_s%>" ;

  var channel = pusher.subscribe(line);
  channel.bind('chat_event', function(data) {
    var user_name = data.name;
    var messagelog = document.getElementById('eventMessages');
    var message = document.createElement('div');
    var info = document.createElement('div');
    info.className = 'user-info';
    var name = document.createElement('p');
    name.className = 'msg-user-name';
    name.innerHTML = data.name;
    var p = document.createElement('p');
    var img01 = document.createElement('img');
    img01.className = 'msg-user-image img-circle';
    $(img01).attr('src','/assets/'+ data.image);
    p.className = 'msg-body';
    p.innerHTML = data.message;
    if(user_name == '<%= current_user.email %>'){
      message.className = 'message my-msg clearfix';
    }else{
      message.className = 'message oth-msg clearfix';
    }

    info.appendChild(img01);
    info.appendChild(name);
    message.appendChild(info);
    message.appendChild(p);
    messagelog.appendChild(message);
    
    var body = document.getElementById('body');
    body.value = '';


  });

</script>
<script>
		function initMap() {
  			var map = new google.maps.Map(document.getElementById('map'), {
	    	center: {lat: <%= @location.latitude %>, lng: <%= @location.longitude %>},
    		zoom: 15,
    		zoomControl: true,
		  	mapTypeControl: true,
 			scaleControl: true,
 			streetViewControl: true,
 			rotateControl: true,
			});
			var marker = new google.maps.Marker({
				position: {lat: <%= @location.latitude %>,lng: <%= @location.longitude %>},
				map: map,
				title: "hello world",
				draggable: true
			});
			// map.addListener('click',function(e){
			// 	// var marker1 = new google.maps.Marker({
			// 	// 	position: e.latLng,
			// 	// 	map: map,
			// 	// 	title: "hello world",
			// 	// 	draggable: true
			// 	// });
			// 	marker.setPosition(e.latLng);
			// 	var position = marker.getPosition();
			// 	var lat = position.lat();
			// 	var lng = position.lng();
			// 	// console.log(position.toString());
			// 	console.log(lat);
			// });
			
		}
	</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCAm2I60JeGDgh48VJFDBuSGrlwfyiqVbA&callback=initMap"></script>