config/routes.rb
Rails.application.routes.draw do

  root 'home#top'

  devise_for :users
  
  resources :users, only:[:index, :edit, :update, :show] do
    resource :relationships, only:[:create, :destroy]
    get :follows, on: :member
    get :folowers, on: :member
  end

  get '/users/:id' => 'users#show'

  
  resources :circles do
    resource :circle_users,only: [:create,:destroy]
    resources :circle_events
    resource :circle_talks,only: :create
    resource :circle_likes,only: [:create,:destroy],as: "likes"
  end



  post "/circle_events/:id/talks" => "circle_event_talks#create",as: "circle_event_talks"
  post "/circles/:circle_id/circle_events/:id/attend" =>"circle_event_tickets#create",as: "circle_event_attend"
  delete "/circles/:circle_id/circle_events/:id/attend" =>"circle_event_tickets#destroy",as: "destroy_circle_event_attend"
  post "/circles/:circle_id/circle_events/:id/attend/:ticket_id" =>"circle_event_tickets#approve",as: "approve_circle_event_attend"

end

app/models/circle.rb
class Circle < ActiveRecord::Base

	mount_uploader :image,ImageUploader

	has_many :circle_users,dependent: :destroy
	has_many :circle_members,through: :circle_users,source: :user
	has_many :circle_events,dependent: :destroy
	has_many :circle_talks,dependent: :destroy

	has_many :circle_likes


	validates :name,presence: true

	validate :add_error_sample

	def add_error_sample
		if name.empty?
			errors[:base] << "サークル名を入力してください"
		end
		if desc.empty?
			errors[:base] << "サークル概要を入力してください"
		end
	end


	def circle_member?(circle,user)
		circle_users.where(circle_id: circle.id,user_id: user.id).exists?
	end

	def circle_liked?(user)
		circle_likes.where(user_id: user.id).exists?
	end

end

app/models/circle_event.rb
class CircleEvent < ActiveRecord::Base

	belongs_to :circle
	belongs_to :author,foreign_key: :author_id,class_name: User

	has_many :circle_event_tickets	
	has_many :circle_event_members,through: :circle_event_tickets,source: :user

	has_many :circle_event_talks

	has_one :circle_event_location

	validates :title,presence: true
	validates :desc,presence: true
	validates :author_id,presence: true


	def event_pending?(event)
		circle_event_tickets.where(circle_event_id: event.id,confirm: false)
	end

	def ticket_status?(circle_event,user,status)
		circle_event_tickets.where(circle_event_id: circle_event.id,user_id: user.id,confirm: status)		
	end

	def event_participants(circle_event)
		circle_event_tickets.where(circle_event_id: circle_event.id,confirm: true)
	end

	mount_uploader :image,CircleEventImageUploader

end

app/models/circle_event_location.rb
class CircleEventLocation < ActiveRecord::Base

	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode

	belongs_to :circle_event

end

app/models/circle_event_talk.rb
class CircleEventTalk < ActiveRecord::Base


	belongs_to :user
	belongs_to :circle_event


end

app/models/circle_event_ticket.rb
class CircleEventTicket < ActiveRecord::Base

	belongs_to :circle_event
	belongs_to :user

	validates :circle_event_id,presence: true
	validates :user_id,uniqueness: { scope: [:circle_event_id] }

end

app/models/circle_like.rb
class CircleLike < ActiveRecord::Base

	belongs_to :user
	belongs_to :circle

	validates :user,presence: true
	validates :user_id,uniqueness: { scope: :circle_id}
	validates :circle,presence: true


end

app/models/circle_talk.rb
class CircleTalk < ActiveRecord::Base

	belongs_to :circle
	belongs_to :user

	validates :circle_id,presence: true
	validates :user_id,presence: true
	validates :body,presence: true


end

app/models/circle_user.rb
class CircleUser < ActiveRecord::Base

	belongs_to :circle
	belongs_to :user

	validates :user_id,uniqueness: { scope: :circle_id }

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: User
	belongs_to :following, class_name: User

	validates :follower_id, presence: true
	validates :following_id, presence: true
	validates :following_id, uniqueness: {scope: :follower_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :relationships, foreign_key: :follower_id
   has_many :followings, through: :relationships

   has_many :inverse_follows, foreign_key: :following_id, class_name: Relationship
   has_many :followers, through: :inverse_follows

   has_many :circle_likes

   has_one :user_prof

   def followed_by? user
   	inverse_follows.where(follower_id: user.id).exists?
   end

  has_many :circle_users,dependent: :destroy
  has_many :circle_talks
  has_many :circle_events
  has_many :circle_event_tickets
  has_many :circle_event_talks
  
end

app/models/user_prof.rb
class UserProf < ActiveRecord::Base

	belongs_to :user


end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  layout "circle"

  before_action :set_circle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /circles
  # GET /circles.json
  def index
    #@circles = Circle.page(params[:page]).per(9)
    @q = Circle.search(params[:q])
    @circles = @q.result(distinct: true).page(params[:page]).per(9)
  end

  # GET /circles/1
  # GET /circles/1.json
  def show
  end

  # GET /circles/new
  def new
    @circle = Circle.new
  end

  # GET /circles/1/edit
  def edit
  end

  # POST /circles
  # POST /circles.json
  def create
    @circle = Circle.new(circle_params)

    respond_to do |format|
      if @circle.save
        format.html { redirect_to @circle, notice: 'サークルが作成されました。' }
        format.json { render :show, status: :created, location: @circle }
      else
        format.html { render :new}
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circles/1
  # PATCH/PUT /circles/1.json
  def update
    respond_to do |format|
      if @circle.update(circle_params)
        format.html { redirect_to @circle, notice: 'サークル情報が更新されました。' }
        format.json { render :show, status: :ok, location: @circle }
      else
        format.html { render :edit }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circles/1
  # DELETE /circles/1.json
  def destroy
    @circle.destroy
    respond_to do |format|
      format.html { redirect_to circles_url, notice: 'サークルが削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circle
      @circle = Circle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circle_params
      params.require(:circle).permit(:name, :image, :desc)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end


	def follows
		@user = User.find(params[:id])
	end
	def followers
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circle_events_helper.rb
module CircleEventsHelper
end

app/helpers/circle_likes_helper.rb
module CircleLikesHelper
end

app/helpers/circle_talks_helper.rb
module CircleTalksHelper
end

app/helpers/circle_users_helper.rb
module CircleUsersHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/_form.html.erb
<%= form_for(@circle) do |f| %>
  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= @circle.errors[:base].count %> 件のエラーがあります。</h2>

      <ul>
      <% @circle.errors[:base].each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" >
    <%= f.label :name,"サークル名",class: "control-label" %>
    <%= f.text_field :name,class: "form-control",placeholder: "サークル名" %>
  </div>
  <div class="field">
    <%= f.label :image,"サークル画像" %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :desc,"サークル概要" %>
    <%= f.text_area :desc,class: "form-control",rows: "3",placeholder: "サークル概要" %>
  </div>
  <div class="actions">
    <%= f.submit submit_message%>
  </div>
<% end %>

app/views/circles/edit.html.erb
<div class="contents-edit">
	<h1>編集</h1>

	<%= render 'form',submit_message: "編集する" %>

	<%= link_to '詳細', @circle %> |
	<%= link_to '一覧へもどる', circles_path %>

</div>

app/views/circles/index.html.erb
<div class="contents-index clearfix">
  <div class="side">
    <%= button_to "サークルを作る",new_circle_path,class: "btn btn-success",method: :get %>
    <div class="side-nav">
      <div class="side-top">
        <h2>サークル一覧</h2>
      </div>
      <!-- /.side-top -->
      <div class="side-content">
        <%= search_form_for @q do |f| %>
        <%= f.search_field :name_or_desc_cont %>
        <%= f.submit %>
        <% end %>
      </div>
      <!-- /.side-content -->
    </div>
    <!-- /.side-nav -->
  </div>
  <!-- /.side -->
  <div class="main clearfix">
    <div class="circles-list clearfix">
      <% @circles.each do |circle| %>
        <div class="circle">
          <% if circle.image? %>
            <%= image_tag circle.image.url,class: "circle-image" %></td>
          <% else %>
            <%= image_tag "circle_img_dafault_gray.png",class: "circle-image"%>
          <% end %>
          <p class="circle-name"><%= circle.name %></p>
          <p class="circle-desc"><%= circle.desc %></p>
          <p class="link-more"><a href="/circles/<%= circle.id %>">もっとみる<i class="fa fa-external-link" aria-hidden="true"></i></a></p>
        </div>
        <!-- /.circle -->
      <% end %>
      <div class="circle-paginate">
        <%= paginate @circles %>
      </div>
    </div>
    <!-- /.circles-list -->
  </div>
  <!-- /.main -->
</div>
<!-- /.contents -->

app/views/circles/new.html.erb
<div class="contents-new">
	<h1>新規作成</h1>

	<%= render 'form',submit_message: "新規作成"%>

	<%= link_to 'サークル一覧へもどる', circles_path %>

</div>

app/views/circles/show.html.erb
<div class="contents-show clearfix">
  <div class="side">
    <div class="side-top">
      <%= button_to "サークル一覧",circles_path,class: "btn btn-primary circles-link",method: :get %>
    </div>
    <!-- /.side-top -->
    <div class="side-contents">
      <% if @circle.image? %>
        <%= image_tag @circle.image.url,class: "circle-image" %></td>
      <% else %>
        <%= image_tag "circle_img_dafault_gray.png",class: "circle-image"%>
      <% end %>
      <div class="circle-status clearfix">
        <p class="circle-user-count"><i class="fa fa-user-plus" aria-hidden="true"></i><%= @circle.circle_members.count %></p>  
        <% if @circle.circle_liked?(current_user) %>
          <p class="circle-likes"><a rel="nofollow" data-method="delete" href="/circles/<%= @circle.id %>/circle_likes"><i class="fa fa-thumbs-up" aria-hidden="true"></i><%= @circle.circle_likes.count %></a></p>
        <% else %>    
          <p class="circle-likes"><a rel="nofollow" data-method="post" href="/circles/<%= @circle.id %>/circle_likes"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i><%= @circle.circle_likes.count %></a></p>   
        <% end %>
      </div>
      <!-- /.circle-status -->
      <p class="circle-name"><%= @circle.name %></p>
      <p class="circle-desc"><%= @circle.desc %></p>
      <% if @circle.circle_member?(@circle,current_user) %>
        <%= button_to "退会する",circle_circle_users_path(@circle.id),class: "btn btn-warning",method: :delete %>
      <% else %>
        <%= button_to "参加する",circle_circle_users_path(@circle.id),class: "btn btn-warning",method: :post %>
      <% end %>
    </div>
    <!-- /.side-contents -->
  </div>
  <!-- /.side -->
  <div class="main">
    <div class="main-contents">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#circle-circle-members" data-toggle="tab">メンバー</a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">主催イベント</a>
            <ul class="dropdown-menu">
              <li><a href="#circle-circle-events" data-toggle="tab">イベント新着</a></li>
              <li><%= link_to 'イベント一覧', circle_circle_events_path(@circle) %></li>
            </ul>
          </li>
        <% if @circle.circle_member?(@circle,current_user) %>
          <li><a data-toggle="modal" data-target="#circleTalk">トーク</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">設定<i class="fa fa-cog" aria-hidden="true"></i></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'サークル編集', edit_circle_path(@circle) %></li>
              <li><%= link_to 'サークル削除', circle_path(@circle),method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="circle-circle-members">
          <div class="circle-member clearfix">
            <% @circle.circle_members.each do |circle_member| %>
              <div class="circle-user">
                <% if circle_member.user_prof.try(:image) %>
                  <%= image_tag circle_member.user_prof.image.url,class: 'user-image img-circle' %>
                <% else %>
                  <%= image_tag 'user_noimage_default.png',class: 'user-image img-circle' %>
                <% end %>
              <p><%= circle_member.email %></p>
              </div>
              <!-- /.circle-user -->
            <% end %>
          </div>
          <!-- /.circle-member -->
        </div>
        <!-- /#circle-circle-member -->
        <div class="tab-pane clearfix" id="circle-circle-events">
          <% @circle.circle_events.limit(10).order('created_at DESC').each do |circle_event| %>
            <div class="circle-event clearfix">
              <% if circle_event.image? %>
                <%= image_tag circle_event.image.url,class: "circle-event-image" %>
              <% else %>
                <%= image_tag "circle_img_dafault_gray.png",class: "circle-event-image" %>
              <% end %>
              <div class="circle-event-prof">
                <p>イベント名: <%= link_to circle_event.title ,circle_circle_event_path(@circle,circle_event) %></p>
                <p>概要:<%= circle_event.desc %></p>
              </div>
              <!-- /.circle-event-prof -->
            </div>
            <!-- /.circle-event -->
          <% end %>
        </div>
        <!-- /#circle-circle-event -->
      </div>
      <!-- /.tab-content -->
    </div>
    <!-- /.main-content -->
  </div>
  <!-- /.main -->
</div>
<!-- /.contents-show -->

<div class="modal fade" id="circleTalk" tabindex="-1" role="dialog" aria-labelledby="circleTalkLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">トーク</h4>
      </div>
      <!-- /.modal-header -->
      <div class="modal-body">
        <div class="clearfix" id='messages'>
          <% @circle.circle_talks.each do |circle_talk| %>
            <% if circle_talk.user.id == current_user.id %>
              <div class="message my-msg clearfix">
                <div class="user-info">
                  <% if current_user.user_prof.try(:image) %>
                    <%= image_tag current_user.user_prof.image.url,class: "msg-user-image img-circle" %>
                  <% else %>
                    <%= image_tag 'user_noimage_default.png',class: "msg-user-image img-circle" %>
                  <% end %>
                  <p class="msg-user-name"><%= circle_talk.user.email%></p>
                </div>
                <p class="msg-body"><%= circle_talk.body %></p>

              </div>
            <% else %>
              <div class="message oth-msg clearfix">
                <div class="user-info">
                  <% if circle_talk.user.user_prof.try(:image) %>
                    <%= image_tag circle_talk.user.user_prof.image.url,class: "msg-user-image img-circle" %>
                  <% else %>
                    <%= image_tag 'user_noimage_default.png',class: "msg-user-image img-circle" %>
                  <% end %>
                  <p class="msg-user-name"><%= circle_talk.user.email%></p>
                </div>
                <p class="msg-body"><%= circle_talk.body %></p>
              </div>
            <% end %>
          <% end %>
        </div>

        <%= form_tag(circle_circle_talks_path(@circle.id),:remote => true) do %>
        <%= text_field_tag :body %>
        <%= submit_tag "送信" %>
        <% end %>
      </div>
      <!-- /.modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      <!-- /.modal-footer -->
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<script>
  Pusher.logToConsole = true;

  var pusher = new Pusher('26f18dcdcf80c348ef52', {
    encrypted: true
  });

  var line = "circle_talk_<%= @circle.id.to_s%>" ;

  var channel = pusher.subscribe(line);
  channel.bind('chat_event', function(data) {
    var user_name = data.name;
    var messagelog = document.getElementById('messages');
    var message = document.createElement('div');
    var info = document.createElement('div');
    info.className = 'user-info';
    var name = document.createElement('p');
    name.className = 'msg-user-name';
    name.innerHTML = data.name;
    var p = document.createElement('p');
    var img01 = document.createElement('img');
    img01.className = 'msg-user-image img-circle';
    $(img01).attr('src','/assets/'+ data.image);
    p.className = 'msg-body';
    p.innerHTML = data.message;
    if(user_name == '<%= current_user.email %>'){
      message.className = 'message my-msg clearfix';
    }else{
      message.className = 'message oth-msg clearfix';
    }

    info.appendChild(img01);
    info.appendChild(name);
    message.appendChild(info);
    message.appendChild(p);
    messagelog.appendChild(message);
    
    var body = document.getElementById('body');
    body.value = '';


  });

</script>
<script>
  // $(function(){
  //   $('')
  //   $('.modal-content').on('show', function(){
  //     var posTop = $('#messages p:last-child').offset()['top'];
  //     var aaa = $('#messages p:last-child').text(); 
  //     console.log(posTop);
  //     console.log(aaa);
  //     $('#messages').scrollTop(posTop);
  //   });
  // });
  $('.modal-open').click(function(){
    var posTop = setTimeout(function(){ $('#messages p:last-child').offset()['top']; }, 3000);
    var aaa = $('#messages p:last-child').text(); 
    console.log(posTop);
    console.log(aaa);
    $('#messages').scrollTop(posTop);
  });
</script>

app/views/users/show.html.erb
<h1>マイページ</h1>

<div>
	名前　：　<%= @user.name %>
</div>
<div>
	所属サークル　: 
</div>